### ISSUE TITLE
外链接地址已失效

### ISSUE THREAD

**Issue by ThomasZB** [XiaobiaoDai/NIRPed#1]
作者你好，我尝试下载数据集时，进入您提供的链接出现外链接地址已失效，还有其他下载途径吗

**Comment by XiaobiaoDai** [comment]
&nbsp;感谢你的反馈。
你可以尝试这个链接：https://pan.baidu.com/s/1l69jut2wJFTRHRqOuFp-nA?pwd=nirp&nbsp;
提取码：nirp&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sat, Oct 28, 2023 02:39 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[XiaobiaoDai/NIRPed] 外链接地址已失效 (Issue #1)

&nbsp;



 
作者你好，我尝试下载数据集时，进入您提供的链接出现外链接地址已失效，还有其他下载途径吗

**Comment by ThomasZB** [comment]
作者您好，我这边提示：该链接已超过访问人数上限，可联系分享者重新分享

**Comment by ThomasZB** [comment]
> &nbsp;感谢你的反馈。 你可以尝试这个链接：https://pan.baidu.com/s/1l69jut2wJFTRHRqOuFp-nA?pwd=nirp&nbsp; 提取码：nirp&nbsp; &nbsp; ------------------&nbsp;Original&nbsp;------------------ From: ***@***.***&gt;; Date: &nbsp;Sat, Oct 28, 2023 02:39 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: &nbsp;[XiaobiaoDai/NIRPed] 外链接地址已失效 (Issue #1) &nbsp; 作者你好，我尝试下载数据集时，进入您提供的链接出现外链接地址已失效，还有其他下载途径吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

作者您好，这个链接也不太行，提示该链接已超过访问人数上限，可联系分享者重新分享/(ㄒoㄒ)/~~

**Comment by XiaobiaoDai** [comment]
不好意思，我重新分享了，你可以尝试这个链接：https://pan.baidu.com/s/1-BEZJ5DsMHFaWElMIPZ_CQ?pwd=nirP&nbsp;
提取码：nirP

&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Oct 31, 2023 04:30 PM
To: ***@***.***&gt;; 
Cc: &nbsp;"Xiaobiao ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [XiaobiaoDai/NIRPed] 外链接地址已失效 (Issue #1)

&nbsp;



  
&nbsp;感谢你的反馈。 你可以尝试这个链接：https://pan.baidu.com/s/1l69jut2wJFTRHRqOuFp-nA?pwd=nirp&nbsp; 提取码：nirp&nbsp; &nbsp; ------------------&nbsp;Original&nbsp;------------------ From: @.&gt;; Date: &nbsp;Sat, Oct 28, 2023 02:39 PM To: @.&gt;; Cc: @.&gt;; Subject: &nbsp;[XiaobiaoDai/NIRPed] 外链接地址已失效 (Issue #1) &nbsp; 作者你好，我尝试下载数据集时，进入您提供的链接出现外链接地址已失效，还有其他下载途径吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
作者您好，这个链接也不太行，提示该链接已超过访问人数上限，可联系分享者重新分享/(ㄒoㄒ)/~~

**Comment by ThomasZB** [comment]
> 不好意思，我重新分享了，你可以尝试这个链接：https://pan.baidu.com/s/1-BEZJ5DsMHFaWElMIPZ_CQ?pwd=nirP&nbsp; 提取码：nirP &nbsp; &nbsp; ------------------&nbsp;Original&nbsp;------------------ From: ***@***.***&gt;; Date: &nbsp;Tue, Oct 31, 2023 04:30 PM To: ***@***.***&gt;; Cc: &nbsp;"Xiaobiao ***@***.***&gt;; ***@***.***&gt;; Subject: &nbsp;Re: [XiaobiaoDai/NIRPed] 外链接地址已失效 (Issue #1) &nbsp; &nbsp;感谢你的反馈。 你可以尝试这个链接：https://pan.baidu.com/s/1l69jut2wJFTRHRqOuFp-nA?pwd=nirp&nbsp; 提取码：nirp&nbsp; &nbsp; ------------------&nbsp;Original&nbsp;------------------ From: @.&gt;; Date: &nbsp;Sat, Oct 28, 2023 02:39 PM To: @.&gt;; Cc: @.&gt;; Subject: &nbsp;[XiaobiaoDai/NIRPed] 外链接地址已失效 (Issue #1) &nbsp; 作者你好，我尝试下载数据集时，进入您提供的链接出现外链接地址已失效，还有其他下载途径吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 作者您好，这个链接也不太行，提示该链接已超过访问人数上限，可联系分享者重新分享/(ㄒoㄒ)/~~ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

谢谢作者o(*￣▽￣*)ブ

**Comment by XiaobiaoDai** [comment]
原来的链接：https://pan.baidu.com/s/1l69jut2wJFTRHRqOuFp-nA?pwd=nirp&nbsp; 提取码：nirp
已经可以使用了，您可以试试。
